kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "youtrack.fullname" . }}-data
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.data.storageClass }}
spec:
  accessModes: {{ .Values.persistence.data.accessModes }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.storageSize }}
