dependencies:
  - name: postgresql
    version: 3.9.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: postgresql.enabled
  - name: redis
    version: 5.4.0
    repository: https://kubernetes-charts.storage.googleapis.com/