apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kadira.fullname" . }}-engine
  labels:
    app.kubernetes.io/name: {{ include "kadira.name" . }}-engine
    helm.sh/chart: {{ include "kadira.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.engine.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kadira.name" . }}-engine
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kadira.name" . }}-engine
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-engine
          image: "{{ .Values.engine.image.repository }}:{{ .Values.engine.image.tag }}"
          imagePullPolicy: {{ .Values.engine.image.pullPolicy }}
          env:
            - name: PORT
              value: "80"
            - name: MONGO_URL
              value: "mongodb://{{ include "kadira.fullname" . }}-mongodb-replicaset:27017/apm?replicaSet=kadira"
            - name: MONGO_SHARD_URL_one
              value: "mongodb://{{ include "kadira.fullname" . }}-mongodb-replicaset:27017/apm?replicaSet=kadira"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.engine.resources | nindent 12 }}
      {{- with .Values.engine.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.engine.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.engine.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
