apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kadira.fullname" . }}-ui
  labels:
    app.kubernetes.io/name: {{ include "kadira.name" . }}-ui
    helm.sh/chart: {{ include "kadira.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ui.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kadira.name" . }}-ui
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kadira.name" . }}-ui
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: PORT
              value: "80"
            - name: MONGO_URL
              value: "mongodb://{{ include "kadira.fullname" . }}-mongodb:27017/apm"
            - name: MONGO_SHARD_URL_one
              value: "mongodb://{{ include "kadira.fullname" . }}-mongodb:27017/apm"
            - name: ROOT_URL
              value: "{{ .Values.ui.rootURL }}"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
