kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "mgob.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "mgob.name" . }}
    helm.sh/chart: {{ include "mgob.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ toYaml .Values.configMap.data | indent 2 }}