{{- range $name, $data := .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  labels:
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
{{- range $name, $value := $data }}
  {{ $name }}: {{ $value | b64enc | quote }}
{{- end }}
---
{{- end }}