apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "mgob.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mgob.name" . }}
    helm.sh/chart: {{ include "mgob.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mgob.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mgob.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-Port=80"
          volumeMounts:
            - name: "mgob-storage"
              mountPath: "/storage"
            - name: "mgob-tmp"
              mountPath: "/tmp"
            - name: "mgob-data"
              mountPath: "/data"
          {{- range $name, $value := .Values.configMap.data }}
            - mountPath: "/config/{{ $name }}"
              name: "mgob-config"
              subPath: {{ $name | quote }}
          {{- end }}
          {{- range $secret := .Values.secret }}
            - mountPath: "/secret/{{ $secret.name }}"
              name: {{ $secret.name }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: "mgob-config"
          configMap:
            name: "mgob-config"
            items:
          {{- range $name, $value := .Values.configMap.data }}
              - key: {{ $name }}
                path: {{ $name }}
          {{- end }}
      {{- range $secret := .Values.secret }}
        - name: {{ $secret.name }}
          secret:
            secretName: {{ $secret.name }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: "mgob-storage"
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.storage.storage.storageClass }}
      spec:
        accessModes:
          - {{ .Values.storage.storage.accessMode }}
        resources:
          requests:
            storage: {{ .Values.storage.storage.size }}
    - metadata:
        name: "mgob-tmp"
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.storage.tmp.storageClass }}
      spec:
        accessModes:
          - {{ .Values.storage.tmp.accessMode }}
        resources:
          requests:
            storage: {{ .Values.storage.tmp.size }}
    - metadata:
        name: "mgob-data"
        annotations:
          volume.beta.kubernetes.io/storage-class: {{ .Values.storage.data.storageClass }}
      spec:
        accessModes:
          - {{ .Values.storage.data.accessMode }}
        resources:
          requests:
            storage: {{ .Values.storage.data.size }}