{{- with .Values.artifactStorage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ default (include "teamcity.fullname" $.) }}-artifacts
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .storageClass }}
spec:
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .storageSize }}
{{- end}}
