{{- $fullName := default (include "teamcity.fullname" .) -}}
{{- with .Values.artifacts_storage }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $fullName }}-artifacts
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .storageClass }}
spec:
  accessModes:
    - {{ .accessMode }}
  resources:
    requests:
      storage: {{ .storageSize }}
{{- end}}
